language: ruby
rvm:
- 2.7.2
install:
  - bundle install
  - nvm install 10
services:
  - postgresql
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
script:
  - bundle exec rspec
